Fix test server build race condition (#134)
graphql-aspnet/graphql-aspnet pull request #135
Opened 2023-11-10 10:13 UTC by Fgruntjes

* Added test project `graphql-aspnet-testframework-tests` for `GraphQL.AspNet.TestFramework` with test case.
* Fixes issue by setting the _pathInitialized at the end of `SchemaItemPath.EnsurePathInitialized()` method.

2023-11-10 17:10 UTC, kevin-carroll requested changes

2023-11-10 17:10 UTC, kevin-carroll commented on src/graphql-aspnet.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "graphql-aspnet-testframework-tests", "unit-tests\graphql-aspnet-testframework-tests\graphql-aspnet-testframework-tests.csproj", "{E67D4FB2-73FF-4E
Can you move the new `graphql-aspnet-testframework-tests` project into the `unit-tests`  solution folder. It keeps the top level a bit cleaner with just the two primary libraries.

2023-11-10 17:13 UTC, kevin-carroll commented
See linting issues on the failed test run.  There is a powershell script `~/build/invoke-pr-build.ps1` that you can execute to swap the ruleset and run the build with the PR linting rule set locally.

2023-11-13 15:08 UTC, Fgruntjes commented
Thanks for the suggestions. Linting errors should be fixed, although I am unsure if git catches adding the BOM.

2023-11-21 14:44 UTC, kevin-carroll approved these changes

2023-11-21 14:45 UTC, merged